### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by adam-lynch** [markdown-it/markdown-it-for-inline#4]
Hey, thanks for the module. Could the documentation be improved please? I would submit a PR but I struggled with using this myself so I'm not the right person. I just [ranted](https://github.com/arve0/markdown-it-implicit-figures/issues/23#issuecomment-341589934) at the poor maintainer of `markdown-it-implicit-figures` who said "you can easily create it yourself with markdown-it-for-inline" 😛

**Comment by puzrin** [comment]
IMHO existing readme + sources are good enougth. But you can ask direct question and i'll try to help.

**Comment by puzrin** [comment]
Clarification: it's very difficult to solve issues without clear criterias (what is good or bad documentation). I tend to avoid such "endless" tickets. But i'm ready to answer any concrete questions, if you have problems with package use.

**Comment by adam-lynch** [comment]
Thanks 😄.

Correct me if I'm wrong but it seems like this plugin would be a lot of people's introduction to dealing with tokens, etc. so I think the docs could do a little bit more to help guide people. Those people might go on to contribute (to this plugin, to markdown-it) or create their own plugins. Some of this could be solved with links to the right markdown-it docs.

Am I understanding this correctly? The rule name is arbitrary. The next param is to filter the `children` of the `inline` token you want to deal with, by `type`. `idx` is said child token's index in the `inline` token's `children`.

Is it intended for this plugin to be used to add tokens? If so, I could submit a PR to add an example?

**Comment by puzrin** [comment]
It's a common pattern to iterate all inline tokens of certain type and to something. This package is for easy prototyping + learning markdown-it.

IMHO readme contains this info + samples.
