### ISSUE TITLE
`build` directory missing from published package for 2.0.0 causes runtime failure when `require` is used

### ISSUE THREAD

**Issue by DavidAnson** [markdown-it/markdown-it-for-inline#6]
`Error: Cannot find module '/Users/runner/work/markdownlint/markdownlint/node_modules/markdown-it-for-inline/build/index.cjs.js'`

<https://github.com/markdown-it/markdown-it-for-inline/blob/8e7eef13c79f3e7931059cf853285bb7e440b900/package.json#L17>

<https://www.npmjs.com/package/markdown-it-for-inline?activeTab=code>

<https://github.com/DavidAnson/markdownlint/actions/runs/7081100389/job/19269891516#step:5:1>

**Comment by DavidAnson** [comment]
FYI, there is an existing test that seems to try to verify this functionality: <https://github.com/markdown-it/markdown-it-for-inline/blob/master/test/cjs.js>. It would be nice to understand why that test did not catch this issue and fix it so it does.

**Comment by puzrin** [comment]
Thank you very much! Released 2.0.1.

I do not have much experience with es6+es5 combined packages. This was the first release of the upcoming bulk org repos update. If something else can be improved - let me know.
